site_name: APL Course
site_description: A guided introduction to Dyalog APL
docs_dir: docs/
site_url: https://dyalog.com
copyright: Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener"><strong>Material for MkDocs</strong></a><br/>Copyright &copy; 1982-$CURRENT_YEAR <strong><a href="https://dyalog.com" target="_blank" rel="noopener">Dyalog Limited</a></strong> (<a href="#" class="copy" onclick="navigator.clipboard.writeText(innerText);return false" title="Click to copy!">$BUILD_DATE $GIT_INFO</a>).<br/>Except where otherwise noted, content on this site is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener"><strong>Creative Commons Attribution 4.0 International</strong></a> licence.
repo_url: https://github.com/Dyalog/APLCourse
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: false
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.superfences
  - abbr
theme:
  name: material
  favicon: 'documentation-assets/images/favicon-32.png'
  language: en
  logo: documentation-assets/images/dyalog-logo_white.svg
  features:
    - navigation.instant
    - content.tooltips
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.sections
extra_css:
  - documentation-assets/css/main.css
  - documentation-assets/css/extra.css
  - documentation-assets/css/admonition-ucmdhelp.css
  - style/main.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/config.js
  - javascripts/mathjax/tex-mml-chtml.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/dyalog
      link: https://dyalog.com
    - icon: material/elephant
      link: https://mastodon.social/@dyalog
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/dyalogapl
plugins:
  - privacy
  - search
  - macros
  - monorepo
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
        reference_text: 'Table {index}'
        caption_prefix: 'Table {index}:'
  - minify:
      minify_html: true
nav:
  - About: index.md
  - basic-syntax-and-arithmetic.md
  - dfns-and-assignment.md
  - array-logic-data-driven-conditionals.md
  - multidimensional-and-nested-arrays.md
  - cells-and-axes.md
  - finding-and-replacing-values.md
  - selecting-from-arrays.md
  - broken-keyboard-problems.md
  - loops-and-recursion.md
  - Extra Assignment: Assignment.md
  - Workspace Basics: Workspaces.md
  - Namespaces and Other Objects: Namespaces.md
  - Getting Help: Help.md
  - User-defined Functions: user-defined-functions.md
  - Operators: Operators.md
  - Quad Names: Quad names.md
  - error-handling-and-debugging.md
  - Data IO: Data.md
  - Code IO: Code.md
  - External Interfaces: Interfaces.md
  - Historical Quirks: Quirks.md
  - Interpreter Internals: Interpreter-internals.md
  - Further Reading: Reading.md
